### ISSUE TITLE
Some questions about code

### ISSUE THREAD

**Issue by ruler9527** [valeoai/3DGenZ#1]
Thank you so much for making your code public!  We are very interested in your work. Could you open the code on S3DIS and Modelnet? In addition, SN_eval and KP-conv_eval files are missing.

**Comment by BjoernMichele** [comment]
Thank you for your interest in our work. 
The eval files for the SN and KP networks you can find in the folders of the respective backbone, they are already there.  Unfortunately I forget to update the links in the README, sorry for that, I will update that. 
My next step is to publish the code for the ZSL classification experiment on ModelNet, that is already in the pipeline.

**Comment by BjoernMichele** [comment]
I updated the links in the README, they work now, sorry for the inconvenience.

**Comment by ruler9527** [comment]
Thanks! In addtion, the train_SemanticKitti.py in 3DGenZ/3DGenZ/genz3d/kpconv/ is missing.

**Comment by BjoernMichele** [comment]
For the training of the KPConv GZSL part on SemanticKITTI, you find the necessary script to launch the training in this folder: 3DGenZ/genz3d/seg/scripts_sk/. 
The therefore necessary:  [semantic word embeddings](https://drive.google.com/file/d/11MMrgWP7OEET8W5GtRYOwKZQ6ihTQp7q/view?usp=sharing) and the [pretrained backbones](https://drive.google.com/file/d/1WyLGAYvUSGnYx0DtRZNozThFqWL7Jgi0/view?usp=sharing). 

If you want to retrain  the KP-Conv backbone, the standard KP-Conv training file can be used but with our adapted dataloader which makes sure, to skip parts which contain unseen classes.
