### ISSUE TITLE
How to compute the Acc in Table 10 and 11?

### ISSUE THREAD

**Issue by Jarrome** [valeoai/3DGenZ#10]
Hi Bjoern,

I'm curious how do you compute the Acc for multi-class? Such as in Table 10 and 11.

Is it TP/(TP+FP) for a class? Which is true_positive_classes[i]/positive_classes[i] for class i using your code variables.

**Comment by BjoernMichele** [comment]
Hello @Jarrome, 

we calculate it, like it is done in ZS3: in genz3d/seg/utils/metrics.py it is the Pixel_Accuracy_Class() function that should do the work, especially the following line. So it is TP/ (TP+FN), as far as I know it can also be seen as a classwise recall.

`Acc_by_class = np.diag(self.confusion_matrix) / self.confusion_matrix.sum(axis=1)`

Have a great day,

**Comment by Jarrome** [comment]
Hi Bjoern,

Many thanks for the details.  :D

I will now close this issue.
