### ISSUE TITLE
About pre-trained models and code on S3DIS dataset?

### ISSUE THREAD

**Issue by ruler9527** [valeoai/3DGenZ#4]
Very nice work, Could you provide the code and pre-trained models on S3DIS dataset? Thank you so much!!

**Comment by ruler9527** [comment]
Hope you can share this part of the code and pretrained model, it will be very helpful to further research!

**Comment by BjoernMichele** [comment]
Thank you very much for your interest in our work. Currently, there is no publishable code for S3DIS in the pipeline. We hope that our descriptions on the selected parameters and the architecture in the paper can also help for further research. Feel free to reach out if I can clearify/give more details with any of them.
Best, 
Bjoern

**Comment by ruler9527** [comment]
Thank you for your answer! Could you provide the pre-trained Convpoint Backbone and ZSL models on S3DIS dataset? I have reproduced them according to the paper (but the results were not ideal) and I want to check the effect. Thanks!

**Comment by BjoernMichele** [comment]
Very nice that you are working with our paper :) I will check, I have conservated project files and will search if I still have that (I have no acess from home so it will be probably next Tuesday or Wednesday before I can give you a definitve answer. Sorry for the delay). 
Best, 
Bjoern

**Comment by ruler9527** [comment]
Thank you very much for your reply! It would be nice to have complete engineering code and pre-trained models in S3DIS datasets!! In addition, if it is not convenient to publish, you can send it to me by email yuwei@stu.scu.edu.cn. Thanks again for your contributions!! We will cite your work in the research!

**Comment by BjoernMichele** [comment]
Solved in exchange with @ruler9527
