### ISSUE TITLE
Question about the environment of convpoint

### ISSUE THREAD

**Issue by ZhengLeon** [valeoai/3DGenZ#5]
Thank you for your work.
I installed all the packages as you guided.
When I try to run '[debug_sn_weight50.sh](https://github.com/valeoai/3DGenZ/blob/master/3DGenZ/genz3d/seg/scripts_sn/debug_sn_weight50.sh)', there is a error about loading 'nearest_neighbors' Could you please help to see what is wrong?
`
Traceback (most recent call last):
  File "/media/SSD/liyang/projects/3DGenZ/3DGenZ/genz3d/seg/train_point_sn.py", line 10, in <module>
    from genz3d.fkaconv.examples.scannet.train import get_data
  File "/media/SSD/liyang/projects/3DGenZ/3DGenZ/genz3d/fkaconv/examples/scannet/train.py", line 23, in <module>
    import genz3d.convpoint.convpoint.knn.lib.python.nearest_neighbors as nearest_neighbors
ModuleNotFoundError: No module named 'genz3d.convpoint.convpoint.knn.lib.python.nearest_neighbors'
`

**Comment by BjoernMichele** [comment]
Dear @ZhengLeon , 

Thank you for your interest in our work. The nearest neighbor function for fkaconv is borrowed from convpoint. Have you run the installation of convpoint ? 

`cd 3DGenZ/genz3d/convpoint/convpoint/knn`

`python3 setup.py install --home="." `

**Comment by ZhengLeon** [comment]
Dear @BjoernMichele,
Thanks for your kind reply.
I think I have installed the convpoint package as it instructs.
Do I need to set the path for 3DGenZ or should I run the training script at the root directory?

**Comment by BjoernMichele** [comment]
Dear @ZhengLeon, 

ok, as I have only seen this error when the convpoint package was not or not correctly installed/compiled. For me, it is not necessary to set the path or to run the training from the root directory. 
I redid the installation from a freshly cloned repository, but I could not reproduce the error. Perhaps, you could compare the outputs you get for the installation with the one I get. 
![installation_3dzsl](https://user-images.githubusercontent.com/29696815/208920675-648504e9-986c-4c56-9a5a-aee68bd99b3f.png)

**Comment by ZhengLeon** [comment]
Dear @BjoernMichele,
Thanks for your instruction. I have fixed the problem now.
I will close this issue.
