### ISSUE TITLE
How to compute the mIOU of each class?

### ISSUE THREAD

**Issue by Jarrome** [valeoai/3DGenZ#6]
In table 10, 12, 13, 14 of 3DGenZ paper, there is a mIOU for each class.

I'm curious how this is computed. Is this actually IOU for whole class?
as [3DGenZ/genz3d/fkaconv/examples/scannet/eval.py](https://github.com/valeoai/3DGenZ/blob/master/3DGenZ/genz3d/fkaconv/examples/scannet/eval.py) did?

Or it averages the IOU  from each point cloud for a class.

**Comment by BjoernMichele** [comment]
Hello @Jarrome, 

Thank you for your interest in our work. 

Yes, the first values in these tables are IoUs per class, values and were calculated as in the eval function you reference. 
Thank you for pointing that out, I will have a deeper look on it again, and see if there is a less misleading way to design the tables, and if applicable updating the supplementary material on Arxiv.

With best regards, 
Bjoern

**Comment by Jarrome** [comment]
Thank you for your fast reply. :D

I will now close this issue as it is addressed!
