### ISSUE TITLE
how to get the evaluation data in S3DIS, the Table 10

### ISSUE THREAD

**Issue by Jarrome** [valeoai/3DGenZ#7]
Hi Bjoern,

How do you split the S3DIS dataset for evaluation in Table. 10?  

Are you using the data from pointnet? For example here https://github.com/charlesq34/pointnet/tree/master/sem_seg

**Comment by BjoernMichele** [comment]
Hello @Jarrome, 

Thank you very much for your interest in our work. 

The validation is done on Area 1.
 Regarding the data, I can not tell directly from your link if it is the same version, as the website they link to, does not load for me ?  

Have a great day. 
Bjoern

**Comment by Jarrome** [comment]
Hi, Bjoern,

Thanks for your quick reply. :D

I find a google drive link: https://drive.google.com/drive/folders/0BweDykwS9vIoUG5nNGRjQmFLTGM?resourcekey=0-dHhRVxB0LDUcUVtASUIgTQ

where there are Stanford3dDataset_v1.2.zip and Stanford3dDataset_v1.2_Aligned_Version.zip.
I guess one of those two files are your test dataset?

My guess is that you compute all rooms in Area 1? just like all scenes in scannet 312 validation scenes. 
Then IoU is computed with TP over the those rooms. 

Very best, my friend
Yijun

**Comment by BjoernMichele** [comment]
Hi Yijun, 

yes, nice that you found them, it seems the official site is not up any more, or ? Yes, that sounds very familiary to me, we used the Aligned version. 
Yes, we used all rooms in Area 1. 
Since a while, I am planning to upload also the code for the S3DIS part. As I have already  sent the uncleaned code to others, I can also send it to you (just provide me your email). 

Have a great day, 
Bjoern

**Comment by Jarrome** [comment]
Hi Bjoern,

I have send you email (to your github verified email address).
Please take a look.

Very best,
Yijun

**Comment by BjoernMichele** [comment]
Yes, thank you, I have sent it to you. The code and script files are attached as a zip, let me know if this is a problem due to firewall etc. 

Have a great day, 
Best, 
Bjoern

**Comment by Jarrome** [comment]
Hi, Bjoern,

I have received the zip. Looks very good!

Sincerely thank you for the help and I will now close this issue.

Very best,
Yijun
