### ISSUE TITLE
Applying for vanilla zero-shot semantic segmentation setting?

### ISSUE THREAD

**Issue by toannguyen1904** [valeoai/3DGenZ#8]
Thanks for your great work. I have a question about whether your approach can be applied to a vanilla semantic segmentation task if the dataset is available. I see in the paper, you said that "we consider semantic segmentation only in the GZSL setting".

**Comment by BjoernMichele** [comment]
Dear @toannguyen1904 , 

Thank you very much for your interest in our work. 

I am not sure if I am correctly understanding your question. Do you mean a vanilla ZSL setting (only unseen classes are appearing at test time ?). If this is the case, I see no problem for our model to handle that. 

However,some of our contributions are targeting the  reduction of bias between seen and unseen classes what is just appearing in the GZSL setting, so you won't need them in the ZSL setting. 

Feel free to reach out, if I can furthermore helo you. 

With best regards, 
Bjoern

**Comment by toannguyen1904** [comment]
Thank you for responding so quickly. You got what I imply in my question and your answer has completely satisfied me.

**Comment by toannguyen1904** [comment]
I reopen this issue to ask more. I see in your framework, the unseen classes are required in training to train the final classifier **f()**. Is that correct? I mean the classes only, not the ground truth of the unseen data.
If this is the case, is it unfair to apply your work to the vanilla ZSL setting?

**Comment by BjoernMichele** [comment]
Hello @toannguyen1904, 

for the unseen classes I only require the auxiliary class information (in my case the word2vec & glove embeddings of the class name). With that information I then can generate representations for these unseen classes that are in the best case close to the representations I would obtain from real instances of the unseen class.
One could differentiate between methods that at train time do not need the auxiliary class information of the unseen classes and methods (like ours) which need it. 
Best regards, 
Bjoern

**Comment by toannguyen1904** [comment]
Thanks very much for the insights!
